### ISSUE TITLE
Yosemite kern extension

### ISSUE THREAD

**Issue by m1entus** [Jonovono/Cutter#2]
Unsigned kexts cannot be used on 10.10 and i'm getting error:

sudo chmod -R 700 /System/Library/Extensions/WavTap.kext
sudo chown -R root:wheel /System/Library/Extensions/WavTap.kext
sudo kextload -v /System/Library/Extensions/WavTap.kext
Requesting load of /System/Library/Extensions/WavTap.kext.
/System/Library/Extensions/WavTap.kext failed to load - (libkern/kext) not loadable (reason unspecified); check the system/kernel logs for errors or try kextutil(8).
make[1]: **\* [install] Error 71
make: **\* [install-kext] Error 2

Have any idea how to install kext in 10.10 ?

**Comment by Jonovono** [comment]
Haven't updated to Yosemite yet. In the next few days i'll give it a try and see if I can get it working and report back.

**Comment by Jonovono** [comment]
@m1entus finally looked into this. So the issue is that apple now requires you to sign the kexts or something.

Anyways found this temporary solution.

Run: sudo nvram boot-args="debug=0x146 kext-dev-mode=1" in your teminal and restart your computer and then try to install cutter again.

Let me know if that works.
